### ISSUE TITLE
MobileDriverManager

### ISSUE THREAD

**Issue by bradyrad** [Magenic/JMAQS#37]
Create MobileDriverManager class/Unit Tests
-PR after AppiumDriverFactory merged in

### Add
- [x] close
- [x] getMobileDriver
- [x] MobileDriverManager(Supplier<AppiumDriver<WebElement>>, TestObject)
- [x] Unit Tests

### Removed
- [x] get (not implemented in JMAQS)

PR #76

**Comment by SudoProgramming** [comment]
#43 Is a blocker for this, but is being removed by @SudoProgramming
