### ISSUE TITLE
SeleniumConfig

### ISSUE THREAD

**Issue by mbfenn** [Magenic/JMAQS#38]
Bring SeleniumConfig up to parity

### Add

- [x] getBrowserType
- [x] getRemoteBrowserType
- [x] getHubUrl
- [x] getWaitDriver
- [x] getSavePagesourceOnFail
- [x] getSoftAssertScreenshot
- [x] getBrowserSize

### Review

- [x] browser
- [x] getScreenshotExtension
- [x] getWaitTime
- [x] getTimeoutTime
- [x] getRemoteCapabilities

**Comment by SudoProgramming** [comment]
#29 was pulled into master, and this issue is now closed.
