### ISSUE TITLE
SeleniumConfig - Unit Tests

### ISSUE THREAD

**Issue by mbfenn** [Magenic/JMAQS#39]
Bring the SeleniumConfig unit tests up to parity

### Add
- [x] getHubUrl
- [x] getRemoteCapabilitiesAsStrings
- [x] getRemoteCapabilitiesAsObjects
- [x] getSavePagesourceOnFail
- [x] getSoftAssertScreenshot

### Review
- [x] getRemotePlatform
- [x] getRemoteBrowserVersion

### Branch/PR:
#29

**Comment by SudoProgramming** [comment]
#29 was pulled into master, and this issue is now closed.
