### ISSUE TITLE
WebServiceDriver

### ISSUE THREAD

**Issue by jonreding2010** [Magenic/JMAQS#57]
Create WebServiceDriver
### Add

- [ ] Create Class
- [ ] List<MediaTypeFormatter> supportedFormatters variable
- [x] Instantiate Class method (HttpClient httpClient)
- [x] Instantiate Class method (Uri baseAddress)
- [ ] Instantiate Class method (string baseAddress)
- [ ] httpClient HttpClient variable
- [ ] getHttpClient method
- [ ] setHttpClient method
- [ ] setCustomMediaFormatters method (params MediaTypeFormatter[] customFormatter)
- [ ] SetCustomMediaFormatters method (List<MediaTypeFormatter> customFormatter)
- [ ] get<T> method (string requestUri, string expectedMediaType, bool expectSuccess = true)
- [ ] get<T> method (string requestUri, string expectedMediaType, HttpStatusCode expectedStatus)
- [ ] get method (string requestUri, string expectedMediaType, bool expectSuccess = true)
- [ ] get method (string requestUri, string expectedMediaType, HttpStatusCode expectedStatus)
- [ ] getWithResponse method (string requestUri, string expectedMediaType, bool expectSuccess = true)
- [ ] getWithResponse method (string requestUri, string expectedMediaType, HttpStatusCode expectedStatus)
- [ ] post<T> method (string requestUri, string expectedMediaType, HttpContent content, bool expectSuccess = true)
- [ ] post<T> method (string requestUri, string expectedMediaType, HttpContent content, HttpStatusCode expectedStatus)
- [ ] post method (string requestUri, string expectedMediaType, HttpContent content, bool expectSuccess = true)
- [ ] post method (string requestUri, string expectedMediaType, HttpContent content, HttpStatusCode expectedStatus)
- [ ] post method (string requestUri, string expectedMediaType, string content, Encoding contentEncoding, string postMediaType, bool contentAsString = true, bool expectSuccess = true)
- [ ] post method (string requestUri, string expectedMediaType, string content, Encoding contentEncoding, string postMediaType, HttpStatusCode expectedStatus, bool contentAsString = true)
- [ ] PostWithResponse method (string requestUri, string expectedMediaType, string content, Encoding contentEncoding, string postMediaType, bool contentAsString = true, bool expectSuccess = true)
- [ ] PostWithResponse method (string requestUri, string expectedMediaType, string content, Encoding contentEncoding, string postMediaType, HttpStatusCode expectedStatus, bool contentAsString = true)
- [ ] PostWithResponse method (string requestUri, string expectedMediaType, HttpContent content, bool expectSuccess = true)
- [ ] PostWithResponse method (string requestUri, string expectedMediaType, HttpContent content, HttpStatusCode expectedStatus)
- [ ] Put<T> method (string requestUri, string expectedMediaType, HttpContent content, bool expectSuccess = true)
- [ ] Put<T> method (string requestUri, string expectedMediaType, HttpContent content, HttpStatusCode expectedStatus)
- [ ] Put method (string requestUri, string expectedMediaType, HttpContent content, bool expectSuccess = true)
- [ ] Put method (string requestUri, string expectedMediaType, HttpContent content, HttpStatusCode expectedStatus)
- [ ] Put method (string requestUri, string expectedMediaType, string content, Encoding contentEncoding, string postMediaType, bool contentAsString = true, bool expectSuccess = true)
- [ ] Put method (string requestUri, string expectedMediaType, string content, Encoding contentEncoding, string postMediaType, HttpStatusCode expectedStatus, bool contentAsString = true)
- [ ] PutWithResponse method (string requestUri, string expectedMediaType, string content, Encoding contentEncoding, string postMediaType, bool contentAsString = true, bool expectSuccess = true)
- [ ] PutWithResponse method (string requestUri, string expectedMediaType, string content, Encoding contentEncoding, string postMediaType, HttpStatusCode expectedStatus, bool contentAsString = true)
- [ ] PutWithResponse(string requestUri, string expectedMediaType, HttpContent content, bool expectSuccess = true)
- [ ] Checkstyle issues (spacing, final variables, line length)
- [ ] Unit Tests

**Comment by jason-edstrom** [comment]
Hold on this one.  This looks like an Epic level issue

**Comment by jonreding2010** [comment]
This may be blocked by WebServiceUtils
